version: '3'

services:
  influxdb-homematic:
    image: influxdb:latest
    container_name: influxdb_homematic
    ports:
      - 8086:8086
    volumes:
      - /influxdb-homematic-db:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_MONITOR_STORE_ENABLED=false
      - INFLUXDB_DB=homematic
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpw
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=userpw
      - INFLUXDB_READ_USER=read
      - INFLUXDB_READ_USER_PASSWORD=readpw
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
  homematic-query:
    image: homematic-query
    container_name: homematic-query
    environment:
      - influx_ip=192.168.1.3
      - influx_port=8086
      - influx_user=user
      - influx_pw=userpw
      - influx_db=homematic
      - hm_ip=192.168.1.5
      - interval=60
    volumes:
       - /grafana/dashboards:/grafana_dashboards:rw
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DATE_FORMATS_FULL_DATE=DD.MM.YYYY HH:mm:ss
      - GF_DATE_FORMATS_INTERVAL_HOUR=DD.MM HH:mm
      - GF_DATE_FORMATS_INTERVAL_MONTH=MM.YYYY
      - GF_DATE_FORMATS_INTERVAL_DAY=DD.MM
    volumes:
      - /grafana:/var/lib/grafana:rw
      - /grafana-provisioning:/etc/grafana/provisioning
